### PR TITLE
Support authenticatorAttachment in PublicKeyCredential

### LINKED ISSUE #249: Support for PublicKeyCredential.authenticatorAttachment
Hi,

In the WebAuthn Level 3 draft, `PublicKeyCredential` contains a new `authenticatorAttachment` field (https://w3c.github.io/webauthn/#iface-pkcredential). I saw that you recently added some WebAuthn 3 bits to the library as experimental (e.g. BE flag), so I'm wondering if `authenticatorAttachment` could be added as well?

If so, I may be able to put up a PR for it. I guess the obvious change is to add the new field to `com.yubico.webauthn.data.PublicKeyCredential`. Some other questions:
- Should the new field (or a getter) be added to more places? E.g. `RegistrationResult` and `AssertionResult`. The caller of the methods that yield those results already has access to `PublicKeyCredential`, but I see that there are getters for other things (e.g. `isBackedUp()`)
- Which tests should be updated to include this?

Any other pointers are welcome.

### PR DESCRIPTION
**Pull request by luisgoncalves**
Fixes #249.

### CODE REVIEW

**Comment by emlun** [comment]
Fixes #249

**Comment by luisgoncalves** [comment]
Failing at  `com.yubico.webauthn.data.JsonIoSpec > The class PublicKeyCredential allows and ignores an authenticatorAttachment attribute.` I'll check.

**Review by emlun — APPROVED** [review]
This looks really good, thanks!

Would you like to be credited in the release notes? And if so, by GitHub username or real name?

**Comment by luisgoncalves** [comment]
Thanks for the help, and for the library.

Sure, why not :) use the GH username.

**Pull request merged**
